### ISSUE TITLE
Design the component playground docs

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/component-playground-docs#3]

**Comment by eliseworthy** [comment]
Suggestion from Eastridge, for all landers: github, npm install and gitter should be on the same position on each lander

**Comment by paulathevalley** [comment]
Ok. All the github links will be in the universal header, at least! Not all projects will have a gitter.

If each project has a different design, then this is going to be tricky. Different type sizes, different hero ideas, different spacing will mean they won’t all align in the same place. This would work if all the landers followed the same branding... do you think this is a good reason to push for the same branding?

**Comment by eliseworthy** [comment]
Maybe I'm being too optimistic, but what I would love to see is a consistent layout and structure for the pages that retains the branding - find the same information at the same place, but with unique styles for each project. So - the heros and spacing taking up the same footprint on the page.. Is this prohibitively restrictive?

**Comment by paulathevalley** [comment]
Ah! Hmmm. Other websites that follow that pattern, same structure and layout but different theming, is the old myspace.com or e-greeting card theme pickers. It can be done, but I’m not confident it can always work, especially as the ecosystem grows but the structure remains rigid. 

If this is important, I would recommend design consistency across all the landers as well—this way we know any new landers will always work. What do you think?

**Comment by paulathevalley** [comment]
I guess this is also coming from a place of growing concerns about the maintainability and sustainability of our lander ecosystem. If we try going with unique aesthetic for each lander, but find out it doesn’t end up working and need to switch to the same design everywhere, the farther down the line we go, the more pain we will experience. 😰

**Comment by paulathevalley** [comment]
...maybe flagships can have unique designs and differing structures (not all OSS projects need playgrounds in the same way that Victory does), but the smaller projects follow the same structure and space branding?

**Comment by eliseworthy** [comment]
Yup, I can totally get on board with that. Do you want to do the component playground in the replicable space theme for smaller projects? Webpack dashboard is kind of a combo - it's very popular but a smaller project. Your call on whether it should should be space or its own thang...

**Comment by paulathevalley** [comment]
Resolved by https://github.com/FormidableLabs/component-playground-docs/pull/8
